#!/usr/bin/env bash

# Fail on first line that fails.
set -e

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
if ! git diff-index --check --cached $against -- ':!*.js.snap' .
then
    echo "Aborting commit due to whitespace errors."
    exit 1
fi

# Only keep staged files that are added (A), copied (C) or modified (M).
STAGED=$(git --no-pager diff --name-only --cached --diff-filter=ACM)
# Files which are only partly staged (eg. git add --patch).
PATCH_STAGED=$(git --no-pager diff --name-only --diff-filter=ACM $STAGED)
# Files which are fully staged.
FULLY_STAGED=$(comm -23 <(echo "$STAGED") <(echo "$PATCH_STAGED"))

JS_STAGED=$(grep -E '.(js|jsx|ts|tsx)$' <<< "$STAGED" || true)
CSS_STAGED=$(grep -E '.(css|scss)$' <<< "$STAGED" || true)
SNAPSHOT_STAGED=$(grep -E '.snap$' <<< "$STAGED" || true)
PRETTIER_STAGED=$(grep -E '.(md|css|scss|js|json|yaml|yml|html)$' <<< "$STAGED" || true)
PRETTIER_FULLY_STAGED=$(grep -E '.(md|css|scss|js|json|yaml|yml|html)$' <<< "$FULLY_STAGED" || true)
PY_STAGED=$(grep -E '.py$' <<< "$STAGED" || true)
PY_FULLY_STAGED=$(grep -E '.py$' <<< "$FULLY_STAGED" || true)

if [ -n "$PRETTIER_FULLY_STAGED" ];
then
  npx prettier --write $PRETTIER_FULLY_STAGED
  git add $PRETTIER_FULLY_STAGED
fi

if [ -n "$PRETTIER_STAGED" ];
then
  npx prettier --check $PRETTIER_STAGED
fi

if [ -n "$PY_FULLY_STAGED" ];
then
    black $PY_FULLY_STAGED
    git add $PY_FULLY_STAGED
fi

if [ -n "$PY_STAGED" ];
then
    black --check $PY_STAGED
fi

if [ -n "$JS_STAGED" ] || [ -n "$CSS_STAGED" ];
then
    npm run build -s
fi

if [ -n "$JS_STAGED" ] || [ -n "$SNAPSHOT_STAGED" ];
then
    npm run test -s
fi
